---
title: "Plan for IATBR analysis"
output: html_document
date: "2024-03-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Simplified model structure

Expanded sample to include 7-year-olds and 14-year-olds.
Combined 2009 and 2017 data sets

Two independence categories:

1. With household adults
2. Without household adults

Two mode categories:

1. Active
2. Motorized

Four combined categories:

1. Active with parent
2. Active without parent
3. Car with parent
4. Car without parent

## Results:

### Unnested model:

* log likelihood: -4220.598
* AIC: 8513.197
* Significant predictors:
    * All three alternative specific constants (reference is car with parent)
    * Age
        * Positive for both independent
        * Negative for active with parent
    * Child's sex
        * Negative for active independent
    * Has older sib
        * Positive for both independent
    * Has younger sib
        * Positive for all
    * Density
        * Positive for both active alternatives
    * Distance
        * Negative for both active alternatives
    * Non-working mom
        * Negative for both independent alternatives
        * Positive for active with parent
    * Vehicle per driver
        * Negative for walk with parent
        * Positive for car without parent
    * Year 2017
        * Negative for walk without parent
        * positive for walk with parent
* Non-significant predictors
    * Income
    * Non-working dad
    
### Mode-based nests:

* log likelihood: -1869.092
* mu_car: (-37.962, 47.112)
* mu_walk: (-0.7955, 3.7355)

### Independence-based nests:

* Failed to converge after 5000 iterations

# Further simplification

Three alternative.
Remove car without parents from sample - this is a total of 65
observations out of 1658 (4%)

## Results:

### Unnested model:

* log likelihood: -4220.598
* AIC: 8513.197
* Significant predictors (same as with four alternatives):
    * Both alternative specific constants (reference is car with parent)
    * Age
        * Positive for active independent
        * Negative for active with parent
    * Child's sex
        * Negative for active independent
    * Density
        * Positive for both active alternatives
    * Distance
        * Negative for both active alternatives
    * Non-working mom
        * Negative for walk alone
        * Positive for walk with parent
    * Vehicle per driver
        * Negative for walk with parent
        
### Mode-based nests:

* log likelihood: -1188.668
* Nests not valid (nesting coefficient not sig greater than one.)

### Independence-based nests:

* log-likelihood: -1188.509
* Nests not valid (nesting coefficient not sig greater than one)

### Cross-nested with alpha = 0.5


