# example generated by ChatGPT

import pandas as pd
import biogeme.database as db
import biogeme.biogeme as bio
import biogeme.models as models
import biogeme.optimization as opt
from biogeme.expressions import Beta

# Read the data from a CSV file
data = pd.read_csv('data.csv')

# Create a database from the data
database = db.Database('data', data)

# Define the IDs and variables of interest
ID = 'ID'
CHOICE = 'Choice'
variables = ['Var1', 'Var2', 'Var3']

# Define the available choices
choices = {'Choice1': 1, 'Choice2': 2, 'Choice3': 3}

# Associate the variables with the database
database.variables = variables

# Define the utility functions
V1 = Beta('V1', 0, None, None, 0)
V2 = Beta('V2', 0, None, None, 0)
V3 = Beta('V3', 0, None, None, 0)

# Define the nests
N1 = Beta('N1', 1, None, None, 0)
N2 = Beta('N2', 1, None, None, 0)

# Define the cross-nested logit model
V = {1: V1, 2: V2, 3: V3}
av = {1: N1, 2: N2}
nests = {1: [1, 2], 2: [3]}

prob = models.cnl_avail(V, av, nests, CHOICE)
logprob = models.log(prob)

# Create the biogeme object
biogeme = bio.BIOGEME(database, logprob)

# Set the algorithm settings
biogeme.modelName = 'cross_nested_logit'
biogeme.generateHtml = False
biogeme.generatePickle = False
biogeme.generateCpp = False

# Estimate the model
results = biogeme.estimate()

# Print the estimated parameters
print('Estimated parameters:')
for param in results.getEstimatedParameters():
    print(f'{param.name}: {param.value:.3f}')
