---
title: "Visualize Biogeme Results"
author: "Carole Voulgaris"
date: "2023-05-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

https://urban-stack.github.io/kids-independent-travel/models/mode-choice/mode-model-biogeme-results.html

## Load libraries

```{r, message=FALSE}
library(tidyverse)
library(here)
library(knitr)
```

## Load Biogeme parameters

```{r, message=FALSE}
bio_results <- here("models",
                    "mode-choice",
                    "biogeme_parameters_mode.csv") |>
  read_csv(show_col_types = FALSE) |>
  rename(Parameter = `...1`) |>
  mutate(sig = case_when(`Rob. p-value` < 0.001 ~ "***",
                         `Rob. p-value` < 0.01 ~ "**",
                         `Rob. p-value` < 0.05 ~ "*",
                         TRUE ~ ""))
  

kable(bio_results, digits = 3)
```

## Load predictions

```{r, message=FALSE}
sim_data <- here("data",
                 "sim-data.csv") |>
  read_csv(show_col_types = FALSE)

predictions <- here("models",
                    "mode-choice",
                    "biogeme_preds_mode.csv") |>
  read_csv(show_col_types = FALSE) |>
  cbind(sim_data)
```

## Visualizations

```{r}

mode_pal <- c("#808080","#b3b3b3", "#e6e6e6")

fn_plot_preds_c <- function(my_preds,
                          to_vary) {
  my_preds |>
    filter(vary == to_vary) |>
    select(c(matches(to_vary), starts_with("Prob. "))) |>
    pivot_longer(cols = starts_with("Prob. "),
                 names_to = "Mode",
                 values_to = "Probability",
                 names_prefix = "Prob. ") |>
    mutate(Mode = factor(Mode, levels = c("bike", "walk", "car"),
                         labels = c("Bike", "Walk", "Car"))) |>
    rename(to_vary = !!to_vary) |>
    ggplot() +
    geom_area(aes(x = to_vary,
                  y = Probability,
                  fill = Mode)) +
    scale_fill_manual(values = mode_pal) +
    theme_minimal() +
    scale_y_continuous(breaks = c(0, 0.5, 1),
                       labels = c("0", "50%", "100%")) 
}

fn_plot_preds_b <- function(my_preds,
                          to_vary) {
  my_preds |>
    filter(vary == to_vary) |>
    select(c(matches(to_vary), starts_with("Prob. "))) |>
    pivot_longer(cols = starts_with("Prob. "),
                 names_to = "Mode",
                 values_to = "Probability",
                 names_prefix = "Prob. ") |>
    mutate(Mode = factor(Mode, levels = c("bike", "walk", "car"),
                         labels = c("Bike", "Walk", "Car"))) |>
    rename(to_vary = !!to_vary) |>
    ggplot() +
    geom_col(aes(x = as_factor(to_vary),
                  y = Probability,
                  fill = Mode),
             position = "stack") +
    scale_fill_manual(values = mode_pal) +
    theme_minimal() +
    scale_y_continuous(breaks = c(0, 0.5, 1),
                       labels = c("0", "50%", "100%")) 
}
  
```

### Vary age

```{r}
fn_plot_preds_c(predictions, "age") +
  scale_x_continuous(name = "Age") 
  
```

### Vary gender

```{r}
fn_plot_preds_b(predictions, "female") +
  scale_x_discrete(name = "Child's gender",
                   labels = c("Male", "Female"))
  
```

### Vary income

```{r}
fn_plot_preds_c(predictions, "income_k") +
  scale_x_continuous(name = "Household income (US$)",
                     breaks = c(0, 125, 250),
                     labels = c("0", "$125 000", "$250,000")) 
  
```

### Vary vehicle access

```{r, warning=FALSE}
fn_plot_preds_c(predictions, "veh_per_driver") +
  scale_x_continuous(name = "Household vehicles per driver",
                     limits = c(0, 2),
                     breaks = c(0, 1, 2)) 
  
```

### Vary number of adults

```{r}
fn_plot_preds_c(predictions, "n_adults") +
  scale_x_continuous(name = "Number of household adults") 
  
```

### Vary distance

```{r}
fn_plot_preds_c(predictions, "distance") +
  scale_x_continuous(name = "Trip distance (km)",
                     breaks = c(0, 1, 2)) 
  
```

### Vary density

```{r}
fn_plot_preds_c(predictions, "density") +
  scale_x_continuous(name = "Population density (people per square km)",
                     breaks = c(0, 6000, 12000),
                     labels = c("0", "6 000", "12 000")) 
  
```
